"""add tour guide assignment

Revision ID: d40a54c84672
Revises: 8acc5ded4d7f
Create Date: 2025-12-18 02:11:19.012771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40a54c84672'
down_revision: Union[str, Sequence[str], None] = '8acc5ded4d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_guide_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'on_duty', 'completed', 'cancelled', name='assignment_status'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_guide_assignments_booking_id'), 'tour_guide_assignments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_tour_guide_assignments_guide_id'), 'tour_guide_assignments', ['guide_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_guide_assignments_guide_id'), table_name='tour_guide_assignments')
    op.drop_index(op.f('ix_tour_guide_assignments_booking_id'), table_name='tour_guide_assignments')
    op.drop_table('tour_guide_assignments')
    # ### end Alembic commands ###
